### ISSUE TITLE
Error: Cannot find module 'tailwindcss-multi-theme'

### ISSUE THREAD

**Issue by ted81das** [miten5/larawind#1]
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Module.require (internal/modules/cjs/loader.js:903:19)
    at require (/home/ted81das/webapps/app-lms/larawind/larawind/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/home/ted81das/webapps/app-lms/larawind/larawind/tailwind.config.js:205:9)
    at Module._compile (/home/ted81das/webapps/app-lms/larawind/larawind/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)

**Comment by Adekabang** [comment]
`npm install tailwindcss-multi-theme `
solve this problem
